version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/:/var/www/agency
    depends_on:
      - mysql
      - php
  php:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    volumes:
      - ./app/:/var/www/agency
  mysql:
    image: mysql:8.0
    ports:
      - "3366:3306"
    env_file:
      - ./docker/mysql/.env
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
